### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by Romulossp** [fduaibs/DevRadar#13]
Olá amigo, desculpe por lhe incomodar em um assunto fora do escopo de seu projeto, mas há um antigo projeto seu que eu utilizava mas não consigo encontra-lo, o "HotmartCourseDownloader" você o descontinuou? Caso o tenha descontinuado poderia passar o projeto upado em outra plataforma para mim fazendo um grande favor?

Muito obrigado.
E Desculpe por incomodá-lo.

**Comment by fduaibs** [comment]
Olá, o projeto foi removido por eu ter tomado strike da plataforma em questão. 

Segue o link no [drive](https://drive.google.com/drive/folders/1SoXtw55_ARCWalq9Ol-cyxTMHIaq3uPx?usp=sharing).

Abraço!
